# Map: basic set, get, len, has
let m = Map[Str, Int].new()
m.set("hello", 1)
m.set("world", 2)
print(m.len())
print(m.get("hello"))
print(m.get("world"))
print(m.get("missing"))
print(m.has("hello"))
print(m.has("missing"))
