# Res[Int, Str]: Ok takes Int (param 0), Err takes Str (param 1)
let a = Res[Int, Str].Val(42)
let b = Res[Int, Str].Err("bad")
print(a)
print(b)

# Res[Str, Int]: Ok takes Str (param 0), Err takes Int (param 1)
let c = Res[Str, Int].Val("good")
let d = Res[Str, Int].Err(99)
print(c)
print(d)
