print(ops.add(1, 2))
print(ops.sub(10, 3))
print(ops.mul(3, 4))
print(ops.div(10, 2))
print(ops.neg(5))
print(ops.not(true))
print(ops.truth(0))
print(ops.truth(1))
print(ops.truth(""))
print(ops.truth("hello"))
print(ops.truth(nil))
print(ops.eq(1, 1))
print(ops.lt(1, 2))
