print(std.ops.add(1, 2))
print(std.ops.sub(10, 3))
print(std.ops.mul(3, 4))
print(std.ops.div(10, 2))
print(std.ops.neg(5))
print(std.ops.not(true))
print(std.ops.truth(0))
print(std.ops.truth(1))
print(std.ops.truth(""))
print(std.ops.truth("hello"))
print(std.ops.truth(nil))
print(std.ops.eq(1, 1))
print(std.ops.lt(1, 2))
